### ISSUE TITLE
Variable "distance_from_top"

### ISSUE THREAD

**Issue by ClimateTools** [nickmckay/LiPD-utilities#11]
The variable "distance_from_top" or "distance" should be interpreted as "depth" in LIPD files.

**Comment by chrismheiser** [comment]
[Juxtlahuaca.Lachniet.2017.zip](https://github.com/nickmckay/LiPD-utilities/files/1069533/Juxtlahuaca.Lachniet.2017.zip)

File given in Slack

**Comment by chrismheiser** [comment]
What was the main issue with this again? Was it because the Time Series data wasn't receiving depth data?

**Comment by khider** [comment]
Yes. The distance was treated as a time series object and the other variables in the file didn't get the "depth" data.

**Comment by chrismheiser** [comment]
Right now, it looks for "distance", "distance_from_top", and "depth" as options for the "depth" key in the time series. The depth data is stored as normal, with its values. 

The only difference is that now there is a time series object for "variableName": "distance_from_top" data that also contains the "depth" values. Previously, this was a time series object for "variableName": "depth". 

A little difficult to explain.

**Comment by chrismheiser** [comment]
Issue #11 fixed in commit : f2923d4
