### ISSUE TITLE
Can't have python files in the R/R folder

### ISSUE THREAD

**Issue by gavinsimpson** [nickmckay/LiPD-utilities#18]
Convention (i.e. `R CMD check`) is that only R code should be in the `R` folder of a package. Currently there is a ~~`bam.py`~~ `bagit.py` file that is required by the package. I suggest this is moved to ~~`R-PKG-ROOT/exec/bam.py`~~ `R-PKG-ROOT/exec/bagit.py` and the R code calling it adjusted so that it knows about the new location.

**Comment by chrismheiser** [comment]
Are you referencing the `bagit.py` by chance? I'm not aware of any `bam.py` files.

**Comment by gavinsimpson** [comment]
Sorry @chrismheiser, I was reading something else and got the files confused. Yes, I mean the `bagit.py` file. I'll edit my original report.
