### ISSUE TITLE
R : collapseTs and calibration data

### ISSUE THREAD

**Issue by chrismheiser** [nickmckay/LiPD-utilities#29]
Calibration data doesn't process through collapseTs because it isn't indexed like interpretation. (ie. "interpretation1_seasonality" vs "calibration_uncertainty")

Should I make some rules to handle calibration as-is (unindexed) or should calibration data be indexed? 

@nickmckay

**Comment by nickmckay** [comment]
I think unindexed because I don't think that a single timeseries can have
more than one...
