### ISSUE TITLE
R:  No automatic pcaMethod install

### ISSUE THREAD

**Issue by chrismheiser** [nickmckay/LiPD-utilities#31]
The pcaMethod package cannot be installed automatically during the geoChronR installation. This has to be done separately before installing geoChronR for unknown reasons. 

There needs to be documentation stating that this is a known bug so users know how to work around it. 

Code: 
source(“https://bioconductor.org/biocLite.R“)
biocLite(“pcaMethods”)

**Comment by nickmckay** [comment]
OK, I think I found a solution for this, it looks like it can be installed from the command line with this line:
devtools::install_git("https://git.bioconductor.org/packages/pcaMethods")

@chrismheiser could you add this line to the instructions before the geoChronR install line?
Also, it looks like the R and RStudio versions are still swapped on the GeoChronR info page

**Comment by gavinsimpson** [comment]
It would be better to provide instructions that require the user to install Bioconductor packages in the normal way via the code @chrismheiser shows - which is also "from the command line". You can't automate this, which is one of the issues with the mismatch between R and Bioconductor releases, so you have to install the Bioconductor packages first and then geoChronR and you might as well do that the official way with biocLite script.

**Comment by chrismheiser** [comment]
This is a GeoChronR issue, not a LiPD Utilities issue. Moving the issue over to GeoChronR repo.
