### ISSUE TITLE
R: warn user about writing ageEnsemble data in paleoData

### ISSUE THREAD

**Issue by nickmckay** [nickmckay/LiPD-utilities#34]
writeLipd() should warn people about writing ageEnsembles that have been mapped into paleoData. This is a common procedure in GeoChronR, and thus will come up, however it can greatly increase the size of the LiPD file, and is easily and quickly replicated upon loading with geoChronR::mapAgeEnsembleToPaleoData() .

Perhaps a warning, and then a yes/no about deleting the ageEnsemble from the paleoData?

**Comment by chrismheiser** [comment]
@nickmckay Should this be a "yes" or "no" parameter to writeLipd or just prompt the user on a file-by-file basis? I'm sure it'll get annoying to answer a lot of prompts if you write a bunch of files at once, but I'm also not sure that there will be a ton of files with ensemble data in Paleo, in which case file-by-file prompts may not be so bad.

Thoughts?

**Comment by nickmckay** [comment]
Hmm,

How about the default is case by case, but there's an "ignore.warnings"
option that's set to FALSE by default in writeLipd()?

**Comment by chrismheiser** [comment]
And if ignore.warnings were set to TRUE, then don't bother to check for ensemble data in paleo? Or remove the ensemble data from paleo and just don't write about it?

**Comment by nickmckay** [comment]
Write it without a warning.
