### ISSUE TITLE
filterTs() limitation

### ISSUE THREAD

**Issue by hanskolus** [nickmckay/LiPD-utilities#35]
Function doesn't appear to work with the OR symbol.

EX) filterTs(TS, 'interpretation1_variable == M | interpretation1_variable == M') 
returns list()

**Comment by chrismheiser** [comment]
Hi @hanskolus ,

Which language are you using this in? This function varies by language. In python you should be able to do a double query like that, but not in R. 

Also, if you have a file I can test with that'd be great! It'd need to be a ZIP type.

**Comment by hanskolus** [comment]
Chris,

Thanks for checking in. I was using R. Do you want me to send you a LiPD
file in ZIP format?

- Hannah

On Mon, Mar 5, 2018 at 7:44 PM, Christopher Heiser <notifications@github.com

**Comment by chrismheiser** [comment]
Yes that would be great. You can upload the file here if you rename the file with a .zip extension, or you can e-mail it to me at heiser@nau.edu

**Comment by hanskolus** [comment]
I've attached an example file. Thanks!

**Comment by chrismheiser** [comment]
I don't see a file attached. Would you mind giving it another try?

**Comment by chrismheiser** [comment]
I should note that if you are replying to the github e-mail notification I'm not sure if the attached files will get sent that way. I think you may need to post to the site page directly or send it to me via regular e-mail.

**Comment by chrismheiser** [comment]
[Aden.Tierney.2013.lpd.zip](https://github.com/nickmckay/LiPD-utilities/files/1786144/Aden.Tierney.2013.lpd.zip)
file

**Comment by chrismheiser** [comment]
The current way to do it is to make two separate calls to filterTs, and group the results into a single list. Like this : 
`new <- c(filterTs(ts, "interpretation == M"), filterTs(ts, "paleoData_variableName == dDwax"))`

I'll see if I can find a simpler way to do it in R, but Python has easier ways to handle multi-expressions that R does not.

**Comment by hanskolus** [comment]
Great, thanks for the clarification!

- Hannah

**Comment by chrismheiser** [comment]
This is no longer relevant. You can now make multiple queries in a single call by adding them to a list and giving that to the function. ie. filterTs(TS, list("query1", query2", ...))
