### ISSUE TITLE
R: the update from 1.2 to 1.3 does not create a scope in the interpretation field

### ISSUE THREAD

**Issue by nickmckay** [nickmckay/LiPD-utilities#36]
It needs to pull the prefix from the interpretation and assign it to scope
This file can be used for testing.

[lonespruce..2012.lpd.zip](https://github.com/nickmckay/LiPD-utilities/files/1764134/lonespruce.2012.lpd.zip)

**Comment by chrismheiser** [comment]
So the new interpretation would have "scope": "climate" ?

**Comment by nickmckay** [comment]
Yep, for climateInterpretation . And whatever is before "Interpretation"
for the generic case.

On Mon, Mar 5, 2018 at 1:36 PM, Christopher Heiser <notifications@github.com
