### ISSUE TITLE
Python: Incorrect inferred data calculations

### ISSUE THREAD

**Issue by chrismheiser** [nickmckay/LiPD-utilities#4]
"For some reason the min/max... of the resolution has NaN and it breaks the JSON and the LiPD uploader"
[MD97-2141.Rosenthal.2003.xlsx](https://github.com/nickmckay/LiPD-utilities/files/1008573/MD97-2141.Rosenthal.2003.xlsx)
[MD97-2141.Rosenthal.2003.zip](https://github.com/nickmckay/LiPD-utilities/files/1008576/MD97-2141.Rosenthal.2003.zip)

**Comment by nickmckay** [comment]
Do you know where this is calculated? Must be in the python utilities... Should be ignoring missing values there

**Comment by chrismheiser** [comment]
Yes it is a Python issue. I should have mentioned that.

**Comment by CommonClimate** [comment]
This is easy to fix with numpy. Are you working with lists or numpy arrays?

Julien Emile-Geay, associate professor
University of Southern California
http://<https://scholar.google.com/citations?user=OVti4jEAAAAJ&hl=en>climdyn.usc.edu<http://climdyn.usc.edu>



On May 17, 2017, at 10:29, Christopher Heiser <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes it is a Python issue. I should have mentioned that.

**Comment by chrismheiser** [comment]
@CommonClimate numpy was actually my first issue. Since it uses non-native data types it was giving me problems when trying to move back to python data types for writeLipds(). I switched to native python max/min/mean/median functions for this, but clearly it doesn't know how to handle NaNs properly.

**Comment by khider** [comment]
Also I have successfully transformed datasets with NaNs without any problems. Not sure what's so special about this file.

**Comment by chrismheiser** [comment]
Reverted to old code that uses numpy module, with some safeguards. Tested.
