### ISSUE TITLE
LiPD utilities in Python not compatible with newer version of numpy

### ISSUE THREAD

**Issue by khider** [nickmckay/LiPD-utilities#43]
<img width="1160" alt="screen shot 2018-07-26 at 6 10 15 pm" src="https://user-images.githubusercontent.com/11758571/43296420-007184f2-9100-11e8-910d-0ac24f018c4f.png">

>>> import lipd as lpd
//anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python3.5/site-packages/lipd/__init__.py", line 13, in <module>
    from lipd.json_viewer import viewLipd
  File "//anaconda/lib/python3.5/site-packages/lipd/json_viewer.py", line 16, in <module>
    from PyQt5 import QtCore
ImportError: dlopen(//anaconda/lib/python3.5/site-packages/PyQt5/QtCore.so, 2): Symbol not found: _PySlice_AdjustIndices
  Referenced from: //anaconda/lib/python3.5/site-packages/PyQt5/QtCore.so
  Expected in: flat namespace
 in //anaconda/lib/python3.5/site-packages/PyQt5/QtCore.so

**Comment by chrismheiser** [comment]
@khider I added specific, working, versions of the package dependencies to setup.py. If you update to LiPD 0.2.5.7, it will have the fixes and should work fine. I tested it in a new environment and it imported.

**Comment by khider** [comment]
After fighting for most of the morning with spyder, which is no longer compatible with the latest PyQT5, I was forced to go back to pyqt5-5.9.2. Since a lot of our users are going to be using Spyder or Jupyter Notebook, I suggest you block the LiPD version to 5.9.2 as well to prevent automatic upgrade.

**Comment by chrismheiser** [comment]
LiPD will only install PyQt5 v5.9 if it needs to. Could another package be updating it? 
```
    install_requires=[
        "bagit==1.5.4",
        "demjson==2.2.4",
        "xlrd==1.1.0",
        "numpy==1.13.1",
        "pandas==0.20.3",
        "requests==2.18.4",
        "sip==4.19.3",
        "PyQt5==5.9",
    ],
```

**Comment by khider** [comment]
Did you check numpy? This is the first warning I get.

**Comment by khider** [comment]
These are the versions I have on my computer now and it's working:
bagit: 1.7.0
demjson: 2.2.4
xlrd: 1.1.0
numpy: 1.15.0
pandas: 0.23.3
requests: 2.19.1
sip: 4.19.8
PyQT5: 5.9.2

**Comment by chrismheiser** [comment]
That's fine. We can stick to 1.15.0 in the requirements.
