### ISSUE TITLE
R: failure to install lipdR in R v 3.6.2

### ISSUE THREAD

**Issue by ebroadman** [nickmckay/LiPD-utilities#52]
When attempting to install lipdR from Github in R v 3.6.2 (MacBook): devtools::install_github("nickmckay/LiPD-Utilities", subdir = "R")

I get the following error:
Error: Failed to install 'lipdR' from GitHub:
  (converted from warning) package ‘Smisc’ is not available (for R version 3.6.2)

**Comment by gavinsimpson** [comment]
*Smisc* was removed from CRAN and archived recently ([Jan 26th, 2020](https://cran.r-project.org/web/packages/Smisc/index.html))

> Package ‘Smisc’ was removed from the CRAN repository.
Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/Smisc/).
Archived on 2020-01-26 as check problems were not corrected in time.

You can install any of the versions previously available on CRAN by downloading the tarball for the relevant version from the archive linked above, but this step needs to be done manually first before you try to install *lipdR*.

**Comment by nickmckay** [comment]
Thanks Ellie and Gavin,

I'm pretty sure we can just replace the function we use from Smisc, but in
the meantime this is a good workaround.

**Comment by ebroadman** [comment]
Nice, thanks to you both.
