### ISSUE TITLE
guess_max = 1e6 causing massive performance issue

### ISSUE THREAD

**Issue by andrewdolman** [nickmckay/LiPD-utilities#57]
There is a massive performance issue using readLipd in R caused by the argument ",guess_max = 1e6" in the call to read_csv in function read_csv_from_file.

Using the example file from http://nickmckay.github.io/LiPD-utilities/r/index.html, which is only 1.3 MB, uses over 7 GB of RAM.

Setting this to 1e3 fixes the problem. 

I would make a pull request but I don't know enough about LiPD to know whether guessing from the first 1000 entries is likely to be good enough.  

```
library(lipdR)

pth <- normalizePath("ODP1098B13.lpd")

dat <- readLipd(pth)
```

**Comment by nickmckay** [comment]
Thanks,

This was changed during troubleshooting, because in some (rare) cases, 1000
isn't enough. However, it shouldn't stay at 1e6 because of the overhead.
I'll look into better solutions.
