### ISSUE TITLE
R: Unable to writeLipd because bagit unsuccessful 

### ISSUE THREAD

**Issue by chrismheiser** [nickmckay/LiPD-utilities#66]
Reported By : Devon Gorbey
OS : Windows (10?)
File : Gorby.CF8.2020

Original issue: 
Windows couldn't find the bagit file, and the process would fail with a message of " No bagit script was set. Skipping bagit..."

Fix attempt 1: 
I sent Devon the bagit.py file, and had him manually save it and set it as an environment variable. 

Resulting issue: 
"Attempted to use bagit but it was unsuccessful. Skipping bagit..."

**Comment by chrismheiser** [comment]
![image001](https://user-images.githubusercontent.com/8582482/82534329-d340e080-9af9-11ea-8a9a-8b53a9b28f1a.png)
![image](https://user-images.githubusercontent.com/8582482/82534334-d50aa400-9af9-11ea-8c7f-13a32ee25239.png)

**Comment by chrismheiser** [comment]
I was able to recreate the issue. I have installed a windows environment so I can start debugging.

**Comment by chrismheiser** [comment]
Issue is resolved. This is not an error with the LiPD Utilities, but rather an issue with a change in how R works on windows.

In order for the Zip module to work on windows, it requires you to install R tools as a separate installation. I checked and could not find a good way to streamline this into an automated installation with the package. The user will have to do this manually. 

I'll get this added to the documentation for the R Quickstart guide. 

Download Link: 
https://cran.r-project.org/bin/windows/Rtools/

**Comment by chrismheiser** [comment]
Added link and note to install R Tools for windows users. Info in guide. E-mailed users who originally opened this ticket so that they know of the resolution.

**Comment by nickmckay** [comment]
Could we check for OS and the installation of that package when running writeLipd(), and then stop and tell the user to install that package if they're on Windows and it's not installed?

**Comment by chrismheiser** [comment]
Devon reported that Rtools solved his issue, so there is confirmation that it works. 

I'll have to check and see if R is able to detect Rtools on installation.

**Comment by chrismheiser** [comment]
Yes, there is a function to detect Rtools, in the "pkgbuild" default library. I'll get that check added in.
