### ISSUE TITLE
lipidR bagit warning

### ISSUE THREAD

**Issue by MichelineCampbell** [nickmckay/LiPD-utilities#71]
Using the example "ODP1098B13.lpd" file and a fresh install of lipdR, ```writeLipid()``` returning ```"Warning: bagit: There was an error while prepping for Bagit: \n Continuing to write LiPD file without bagging Error in get(\"bagit.script\", .GlobalEnv): object 'bagit.script' not found\n"```. New to LiPD, so no idea if this normal/fine or not :)

**Comment by nickmckay** [comment]
Yes,

This warning happens if you don't have an optional piece of the lipd
writing installed on your computer, and shouldn't cause any problems,
you can safely ignore this.

**Comment by MichelineCampbell** [comment]
Thanks!
