### ISSUE TITLE
Python: ExtractTs no longer working

### ISSUE THREAD

**Issue by michaelerb** [nickmckay/LiPD-utilities#72]
With the recent update, ExtractTs is no longer working for me.  I get the following error:

extracting paleoData...
Error: Unable to extractTs: name 'start' is not defined

The error appears to be because the variable "start" is never defined in the code, but the code tries to use it as an input for the "extract" function.  Formerly, "start" was defined using the clock function, but that line was removed in the most recent update.  Please fix.

**Comment by michaelerb** [comment]
For a quick fix, I added the line "start = clock()" back to the beginning of ExtractTs on my local copy of __init__.py.  Is this an adequate fix?  I'm not entirely sure what the "start" variable is used for.

**Comment by chrismheiser** [comment]
Hi Michael,

Sorry you had to deal with this bug. It's since been fixed (officially) in an update if you install the most recent LiPD package 0.2.8.1. You were correct to add that line back in. I use that as the timestamp for identifying new Time Series, and mistakenly removed it.
