### ISSUE TITLE
R: fails to install LipdR

### ISSUE THREAD

**Issue by MBuss32** [nickmckay/LiPD-utilities#74]
Hi,
I'm trying to install the LiPDR package as I'd like to start playing with it (I dont have much coding experience) but I'm getting the following error when installing via devtools. (also via 'remotes' it doesn't work as suggested in other topic):
Any help?
Thanks! Manuel

> devtools::install_github("nickmckay/LiPD-Utilities", subdir = "R")
Downloading GitHub repo nickmckay/LiPD-Utilities@HEAD
✓  checking for file ‘/private/var/folders/jr/2f4g184x2b1_h9ylb9zlh5ym0000gn/T/Rtmp3JmXu8/remotes11e92c95aed6/nickmckay-LiPD-utilities-ab7d661/R/DESCRIPTION’ (346ms)
─  preparing ‘lipdR’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘lipdR_0.2.3.tar.gz’
   
* installing *source* package ‘lipdR’ ...
** using staged installation
** R
** exec
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘lipdR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/lipdR’
Error: Failed to install 'lipdR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/jr/2f4g184x2b1_h9ylb9zlh5ym0000gn/T//Rtmp3JmXu8/file11e917097a78/lipdR_0.2.3.tar.gz’ had non-zero exit status

**Comment by MBuss32** [comment]
oops, solved it, hadnt updated R and RStudio to latest version, it works now

**Comment by nickmckay** [comment]
Great,

Glad it's working. Let us know if you run into any other bugs or issues.
