### ISSUE TITLE
Python: Conflict with PyQT. 

### ISSUE THREAD

**Issue by khider** [nickmckay/LiPD-utilities#75]
Installing lipd creates environment conflict with Spyder, which is a widely used IDE. Can we find a replacement for this dependency?

**Comment by michaelerb** [comment]
I have this problem too, and I think this is going to cause issues with lots of python/lipd users, so it should be looked into.

**Comment by chrismheiser** [comment]
PyQT5 only had one requirement in viewLipd(). I removed the dependency for the lipd package and the occurrences as of 0.2.8.3

**Comment by CommonClimate** [comment]
Hallelujah! Thanks @chrismheiser !

**Comment by michaelerb** [comment]
Great!  However, when I try to use this version, I get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/pd_lab/mpe32/conda/envs/python3/lib/python3.8/site-packages/lipd/__init__.py", line 19, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)

The command "from time import clock" doesn't seem to work.  When I look at my older version of the code, uses the command "from time import process_time as clock" instead.
