### ISSUE TITLE
Python: No resolution calculated

### ISSUE THREAD

**Issue by chrismheiser** [nickmckay/LiPD-utilities#9]
> For some reasons the resolution didn't get calculated on this file
- Deborah

[ODP658.Sarnthein.1989.xlsx](https://github.com/nickmckay/LiPD-utilities/files/1058682/ODP658.Sarnthein.1989.xlsx)
[ODP658.Sarnthein.1989.zip](https://github.com/nickmckay/LiPD-utilities/files/1058684/ODP658.Sarnthein.1989.zip)

**Comment by chrismheiser** [comment]
Looks like the code is working as intended, but maybe not the way you want. Resolutions are calculated when there is a year, age, yr bp column in the table OR if a column has an inferredVariableType of year or age. 

Table 1: No age, year, yr bp in any column. 
Table 2: Found "LR04 age" and calculated resolution. 

Is there a new rule that needs to be added or am I missing something?

**Comment by khider** [comment]
@chrismheiser I thought in this case it would return a missing value rather than just leave it blank. My bad.

**Comment by chrismheiser** [comment]
Oh, I see. That's not how it's written. I'm open to doing that, though I find it easier to leave it out when not needing it. Is that something that the wiki would benefit from?

**Comment by khider** [comment]
That's something other people could benefit from. Blank on the wiki means the data/metadata was not given. In this case, it's not available (uncalculable).

**Comment by chrismheiser** [comment]
So you want this for **every** column? 

`                    "hasMaxValue" : 'NaN',
                    "hasMeanValue" : 'NaN',
                    "hasMedianValue" : 'NaN',
                    "hasMinValue" : 'NaN',
                    "hasResolution" : { 
                        "hasMaxValue" : 'NaN',
                        "hasMeanValue" : 'NaN',
                        "hasMedianValue" : 'NaN',
                        "hasMinValue" : 'NaN'
                      },`

**Comment by khider** [comment]
well, no for the hasMaxValue and so on. Regardless of whether there is an age column, the column should have its own values.
But yes for the HasResolution dictionary
